server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mingkaili/microservice/
          search-paths: config-repo
          username: lmk57320402@126.com
          password: 1234567890ppPP