server:
  port: 8021
spring:
  application:
    name: microservice-consumer-hystrix-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true

