# https://blog.csdn.net/tianyaleixiaowu/article/details/78184793 高可用教程
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/