spring:
  application:
    name: microservice-hystrix-turbine
server:
  port: 8031
turbine:
  appConfig: microservice-consumer-hystrix-ribbon,microservice-consumer-hystrix-feign
  combine-host-port: true
  clusterNameExpression: "'default'"
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/